### PR TITLE
Add support for IAM users and roles

### PR DESCRIPTION
**Pull request by svaranasi-traderev**
Adding support to tag IAM users and IAM roles. 

Plus, changing the Lambda runtime from Nodejs6.10 to Nodejs8.10 as AWS has dropped support for the former. This code seems to be compatible with Nodejs8.10 runtime as well.

NOTE: First time Nodejs coder here. Open to suggestions and improvements to the code I'm submitting.

### CODE REVIEW

**Comment by svaranasi-traderev** [comment]
> Nice work! thanks!

Thanks for the feedback! How does this get merged?

**Comment by rayj-pgi** [comment]
we need @em0ney to merge it for us...

**Comment by rayj-pgi** [comment]
I just checked in with him directly, we'll see that works...

**Comment by em0ney** [comment]
Sorry for the delay! This looks good. Thanks for your work.

I'm promoting @rayj-pgi to become a maintainer to help me out!

**Pull request merged**
